"use client";

import { BlendMode, PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { CATEGORIES } from "@/lib/categories";
import type { BookAnalysis, PlacedAnnotation } from "@/lib/types";
import { GUTTER_X } from "./textToPdf";

const NOTE_SIZE = 9;
const NOTE_LINE = 11;
const EXTRA_GUTTER = 170; // widening applied to uploaded PDFs with no free margin

/**
 * Bake highlights + margin notes into a copy of the PDF and prepend a
 * summary page. Rects are already in PDF user space (bottom-left origin),
 * the same space pdf-lib draws in, so they transfer 1:1.
 */
export async function exportAnnotatedPdf(args: {
  pdfBytes: ArrayBuffer;
  title: string;
  author: string;
  analysis: BookAnalysis | null;
  /** page (1-based) → placed annotations for that page */
  placedByPage: Map<number, PlacedAnnotation[]>;
  /** true when the PDF was generated by us and already has a wide right gutter */
  hasBuiltInGutter: boolean;
}): Promise<Uint8Array> {
  const doc = await PDFDocument.load(args.pdfBytes);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const pages = doc.getPages();
  for (const [pageNo, anns] of args.placedByPage) {
    const page = pages[pageNo - 1];
    if (!page || anns.length === 0) continue;

    let gutterX: number;
    if (args.hasBuiltInGutter) {
      gutterX = GUTTER_X;
    } else {
      const { width, height } = page.getSize();
      page.setSize(width + EXTRA_GUTTER, height);
      gutterX = width + 8;
    }
    const gutterW = page.getSize().width - gutterX - 10;

    // Highlights
    for (const ann of anns) {
      const [r, g, b] = CATEGORIES[ann.category].rgb;
      for (const rect of ann.rects) {
        page.drawRectangle({
          x: rect.x,
          y: rect.y,
          width: rect.w,
          height: rect.h,
          color: rgb(r, g, b),
          opacity: 0.35,
          blendMode: BlendMode.Multiply,
        });
      }
    }

    // Margin notes, stacked near their highlight's y (top-down)
    const sorted = [...anns].sort((a, b) => {
      const ya = a.rects[0]?.y ?? 0;
      const yb = b.rects[0]?.y ?? 0;
      return yb - ya;
    });
    let cursorY = page.getSize().height - 50;
    for (const ann of sorted) {
      const [r, g, b] = CATEGORIES[ann.category].rgb;
      const anchor = ann.rects[0];
      const desiredY = anchor ? anchor.y + anchor.h - NOTE_LINE : cursorY;
      const y = Math.min(desiredY, cursorY);
      const noteText = sanitizeAnsi(
        ann.rects.length
          ? ann.margin_note
          : `${ann.margin_note} (near: "${ann.exact_quote.split(" ").slice(0, 5).join(" ")}...")`,
      );
      const lines = wrapText(noteText, bold, NOTE_SIZE, gutterW);
      let ly = y;
      // Category swatch
      page.drawRectangle({
        x: gutterX - 6,
        y: y - (lines.length - 1) * NOTE_LINE - 2,
        width: 3,
        height: lines.length * NOTE_LINE,
        color: rgb(r, g, b),
      });
      for (const line of lines) {
        if (ly < 20) break;
        page.drawText(line, {
          x: gutterX,
          y: ly,
          size: NOTE_SIZE,
          font: bold,
          color: rgb(0.15, 0.15, 0.15),
        });
        ly -= NOTE_LINE;
      }
      // Leader line from note to highlight
      if (anchor) {
        page.drawLine({
          start: { x: gutterX - 8, y: y + 3 },
          end: { x: anchor.x + anchor.w, y: anchor.y + anchor.h / 2 },
          thickness: 0.6,
          color: rgb(r * 0.7, g * 0.7, b * 0.7),
          opacity: 0.8,
        });
      }
      cursorY = y - lines.length * NOTE_LINE - 8;
    }
  }

  if (args.analysis) {
    prependSummaryPage(doc, font, bold, args);
  }

  return doc.save();
}

function wrapText(
  text: string,
  font: { widthOfTextAtSize(t: string, s: number): number },
  size: number,
  maxWidth: number,
): string[] {
  const words = text.split(" ");
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    const cand = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(cand, size) <= maxWidth || !line) line = cand;
    else {
      lines.push(line);
      line = word;
    }
  }
  if (line) lines.push(line);
  return lines;
}

const ANSI_MAP: Record<string, string> = {
  "‘": "'", "’": "'", "“": '"', "”": '"',
  "–": "-", "—": "--", "…": "...", " ": " ",
};

function sanitizeAnsi(s: string): string {
  let out = "";
  for (const c of s) {
    if (ANSI_MAP[c] !== undefined) out += ANSI_MAP[c];
    else if (c.charCodeAt(0) < 0x100) out += c;
    else {
      const d = c.normalize("NFKD").replace(/[̀-ͯ]/g, "");
      out += d.charCodeAt(0) < 0x100 ? d : "?";
    }
  }
  return out;
}

function prependSummaryPage(
  doc: PDFDocument,
  font: Awaited<ReturnType<PDFDocument["embedFont"]>>,
  bold: Awaited<ReturnType<PDFDocument["embedFont"]>>,
  args: { title: string; author: string; analysis: BookAnalysis | null },
) {
  const a = args.analysis;
  if (!a) return;
  const page = doc.insertPage(0, [612, 792]);
  let y = 740;
  const draw = (text: string, opts: { size?: number; b?: boolean; color?: [number, number, number] } = {}) => {
    const size = opts.size ?? 10;
    const f = opts.b ? bold : font;
    for (const line of wrapText(sanitizeAnsi(text), f, size, 512)) {
      if (y < 40) return;
      page.drawText(line, {
        x: 50,
        y,
        size,
        font: f,
        color: rgb(...(opts.color ?? [0.12, 0.12, 0.12])),
      });
      y -= size + 4;
    }
  };

  draw(`${args.title}`, { size: 20, b: true });
  draw(`by ${args.author} — study guide`, { size: 11, color: [0.4, 0.4, 0.4] });
  y -= 10;
  draw("Summary", { size: 13, b: true });
  draw(a.summary);
  y -= 8;
  draw("Setting", { size: 13, b: true });
  draw(`${a.setting.time} — ${a.setting.place}. ${a.setting.description}`);
  y -= 8;
  draw("Main characters", { size: 13, b: true });
  for (const c of a.characters.slice(0, 10)) draw(`• ${c.name} (${c.role}): ${c.description}`);
  y -= 8;
  draw("Conflict", { size: 13, b: true });
  draw(`${a.conflict.type}: ${a.conflict.description}`);
  y -= 8;
  draw("Themes", { size: 13, b: true });
  for (const t of a.themes.slice(0, 6)) draw(`• ${t.theme}: ${t.explanation}`);
}

export function downloadBytes(bytes: Uint8Array, filename: string) {
  const copy = new Uint8Array(bytes); // detach-safe standalone buffer
  const blob = new Blob([copy], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
