import type {
  Article,
  Briefing,
  Claim,
  Conflict,
  Country,
  Incident,
  NewsCluster,
  OfficialAddress,
  Source,
} from "./types";

/**
 * Demo/fixture dataset — a FICTIONAL scenario.
 *
 * Every record carries `demo: true` and the UI shows a persistent
 * "Demo data — fictional scenario" banner. Countries use ISO 3166 private-use
 * codes (X*), and all states, ministries, outlets, and events are invented.
 * This is deliberate: the product rule "never fabricate current events" means
 * fixtures must never imitate real-world news.
 *
 * All timestamps are computed relative to `now` so every lifecycle state
 * (upcoming, live, embargoed, expired-embargo, archived…) is exercised no
 * matter when the app runs. Pass a fixed `now` in tests for determinism.
 */

const min = 60_000;
const hour = 60 * min;
const day = 24 * hour;

function iso(now: Date, offsetMs: number): string {
  return new Date(now.getTime() + offsetMs).toISOString();
}

export interface FixtureSet {
  countries: Country[];
  conflicts: Conflict[];
  sources: Source[];
  articles: Article[];
  claims: Claim[];
  incidents: Incident[];
  newsClusters: NewsCluster[];
  addresses: OfficialAddress[];
  briefings: Briefing[];
}

export function buildFixtures(now: Date): FixtureSet {
  const countries: Country[] = [
    { code: "XA", name: "Ardenia", region: "Western Meridian", demo: true },
    { code: "XV", name: "Velmar", region: "Western Meridian", demo: true },
    { code: "XK", name: "Koris", region: "Eastern Sund Basin", demo: true },
    { code: "XS", name: "Sundara", region: "Sahel Coast", demo: true },
    { code: "XN", name: "Nerath", region: "Western Meridian", demo: true },
  ];

  const conflicts: Conflict[] = [
    {
      id: "cf-ardenia-velmar",
      name: "Ardenia–Velmar border conflict",
      region: "Western Meridian",
      countryCodes: ["XA", "XV"],
      summary:
        "A fictional interstate conflict over the Kessel border region, used to demonstrate the app. Strikes, interceptions, and negotiation tracks are all invented.",
      demo: true,
    },
    {
      id: "cf-koris-unrest",
      name: "Koris civil unrest",
      region: "Eastern Sund Basin",
      countryCodes: ["XK"],
      summary:
        "Fictional nationwide protests in Koris following disputed election results.",
      demo: true,
    },
    {
      id: "cf-sundara-humanitarian",
      name: "Sundara flood emergency",
      region: "Sahel Coast",
      countryCodes: ["XS"],
      summary:
        "Fictional humanitarian emergency after severe flooding displaced communities in southern Sundara. Disaster context only — not conflict evidence.",
      demo: true,
    },
  ];

  const sources: Source[] = [
    {
      id: "s-meridian-wire",
      name: "Meridian Wire",
      type: "wire-service",
      domains: ["meridianwire.example"],
      languages: ["en"],
      licenseNotes: "Demo fixture. Metadata + short excerpts only.",
      attributionRequirements: "Name publisher and link original.",
      refreshIntervalMinutes: 5,
      parserVersion: "fixture-1",
      health: "healthy",
      reliabilityNotes: "Fictional wire service with strong correction record.",
      editorialApproval: "approved",
      countsAsEvidence: true,
    },
    {
      id: "s-continental",
      name: "The Continental Observer",
      type: "national-outlet",
      domains: ["continentalobserver.example"],
      languages: ["en"],
      licenseNotes: "Demo fixture. Metadata + short excerpts only.",
      attributionRequirements: "Name publisher and link original.",
      refreshIntervalMinutes: 15,
      parserVersion: "fixture-1",
      health: "healthy",
      reliabilityNotes: "Fictional broadsheet with field correspondents.",
      editorialApproval: "approved",
      countsAsEvidence: true,
    },
    {
      id: "s-koris-daily",
      name: "Koris Daily Post",
      type: "local-outlet",
      domains: ["korisdaily.example"],
      languages: ["en"],
      licenseNotes: "Demo fixture. Syndicates wire copy under license.",
      attributionRequirements: "Name publisher and link original.",
      refreshIntervalMinutes: 30,
      parserVersion: "fixture-1",
      health: "degraded",
      reliabilityNotes: "Fictional local outlet; frequently syndicates Meridian Wire.",
      editorialApproval: "approved",
      countsAsEvidence: true,
    },
    {
      id: "s-ardenia-mod",
      name: "Ardenia Ministry of Defense",
      type: "official-military",
      domains: ["mod.ardenia.example"],
      languages: ["en"],
      licenseNotes: "Official statements; public record.",
      attributionRequirements: "Attribute as claim by the named ministry.",
      refreshIntervalMinutes: 10,
      parserVersion: "fixture-1",
      health: "healthy",
      reliabilityNotes:
        "Party to the fictional conflict. Statements are primary claims, never independent corroboration.",
      editorialApproval: "approved",
      countsAsEvidence: false,
    },
    {
      id: "s-velmar-gov",
      name: "Velmar Government Press Office",
      type: "official-government",
      domains: ["press.velmar.example"],
      languages: ["en"],
      licenseNotes: "Official statements; public record.",
      attributionRequirements: "Attribute as claim by the named office.",
      refreshIntervalMinutes: 10,
      parserVersion: "fixture-1",
      health: "healthy",
      reliabilityNotes:
        "Party to the fictional conflict. Statements are primary claims, never independent corroboration.",
      editorialApproval: "approved",
      countsAsEvidence: false,
    },
    {
      id: "s-united-assembly",
      name: "United Assembly Press",
      type: "international-organization",
      domains: ["press.unitedassembly.example"],
      languages: ["en", "fr"],
      licenseNotes: "Public-record remarks and schedules.",
      attributionRequirements: "Name the speaker and body.",
      refreshIntervalMinutes: 30,
      parserVersion: "fixture-1",
      health: "healthy",
      reliabilityNotes: "Fictional UN-analog press office.",
      editorialApproval: "approved",
      countsAsEvidence: true,
    },
    {
      id: "s-irc",
      name: "International Relief Coalition",
      type: "humanitarian-ngo",
      domains: ["reports.irc-demo.example"],
      languages: ["en"],
      licenseNotes: "Situation reports; open licence with attribution.",
      attributionRequirements: "Name organization and report.",
      refreshIntervalMinutes: 60,
      parserVersion: "fixture-1",
      health: "healthy",
      reliabilityNotes: "Fictional ICRC/OCHA-analog relief coalition.",
      editorialApproval: "approved",
      countsAsEvidence: true,
    },
    {
      id: "s-aggregator",
      name: "Global Event Aggregator",
      type: "aggregator",
      domains: ["gea.example"],
      languages: ["multi"],
      licenseNotes: "Discovery metadata only.",
      attributionRequirements: "n/a",
      refreshIntervalMinutes: 15,
      parserVersion: "fixture-1",
      health: "healthy",
      reliabilityNotes:
        "GDELT-analog. Discovery and clustering signal only — never evidence, never corroboration.",
      editorialApproval: "approved",
      countsAsEvidence: false,
    },
  ];

  let artSeq = 0;
  function art(
    sourceId: string,
    publisher: string,
    title: string,
    publishedOffsetMs: number,
    opts: Partial<Article> = {},
  ): Article {
    const id = `art-${++artSeq}`;
    const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 48);
    const url = `https://${publisher.toLowerCase().replace(/[^a-z0-9]+/g, "")}.example/${slug}`;
    return {
      id,
      sourceId,
      url,
      canonicalUrl: url,
      publisher,
      title,
      language: "en",
      publishedAt: iso(now, publishedOffsetMs),
      retrievedAt: iso(now, publishedOffsetMs + 4 * min),
      contentHash: `h-${id}`,
      ...opts,
    };
  }

  // --- Kessel strike article set: 2 independent outlets, 1 syndicated copy,
  // 2 official claims (parties, excluded from independence), 1 aggregator hit.
  const aKesselWire = art(
    "s-meridian-wire",
    "Meridian Wire",
    "Strikes reported in Northern Kessel Province",
    -26 * hour,
  );
  const aKesselObserver = art(
    "s-continental",
    "The Continental Observer",
    "Blasts heard across Northern Kessel, residents say",
    -25 * hour,
  );
  const aKesselSynd = art(
    "s-koris-daily",
    "Koris Daily Post",
    "Strikes reported in Northern Kessel Province",
    -24 * hour,
    { syndicatedFromArticleId: aKesselWire.id, contentHash: aKesselWire.contentHash },
  );
  const aKesselMod = art(
    "s-ardenia-mod",
    "Ardenia Ministry of Defense",
    "Statement on operations in the Kessel sector",
    -24 * hour,
  );
  const aKesselDenial = art(
    "s-velmar-gov",
    "Velmar Government Press Office",
    "Velmar disputes reported casualty figures",
    -22 * hour,
  );
  const aKesselAgg = art(
    "s-aggregator",
    "Global Event Aggregator",
    "Cluster: Kessel province event mentions",
    -25 * hour,
  );

  const aDrone = art(
    "s-meridian-wire",
    "Meridian Wire",
    "Drone activity reported near Port Havren",
    -7 * hour,
  );
  const aGround1 = art(
    "s-meridian-wire",
    "Meridian Wire",
    "Fighting reported along northern contact line",
    -11 * hour,
  );
  const aGround2 = art(
    "s-continental",
    "The Continental Observer",
    "Shelling exchanges continue in border districts",
    -10 * hour,
  );
  const aNaval = art(
    "s-continental",
    "The Continental Observer",
    "Cargo vessel reports incident in Aris Strait",
    -15 * hour,
  );
  const aExplosion = art(
    "s-koris-daily",
    "Koris Daily Post",
    "Explosion reported in Velmar City industrial zone; cause unknown",
    -9 * hour,
  );
  const aIntercept1 = art(
    "s-meridian-wire",
    "Meridian Wire",
    "Air defenses active over Ardenia capital region",
    -13 * hour,
  );
  const aIntercept2 = art(
    "s-continental",
    "The Continental Observer",
    "Interceptions reported over Ardenia; no ground impact confirmed",
    -12 * hour,
  );
  const aIntercept3 = art(
    "s-ardenia-mod",
    "Ardenia Ministry of Defense",
    "Air-defense engagement summary",
    -12 * hour,
  );
  const aUnrest1 = art(
    "s-koris-daily",
    "Koris Daily Post",
    "Large crowds gather in Koris capital for third day",
    -30 * hour,
  );
  const aUnrest2 = art(
    "s-meridian-wire",
    "Meridian Wire",
    "Koris protests continue after disputed vote",
    -29 * hour,
  );
  const aCyber = art(
    "s-continental",
    "The Continental Observer",
    "Velmar utility reports service disruption; attribution unclear",
    -20 * hour,
  );
  const aTalks1 = art(
    "s-united-assembly",
    "United Assembly Press",
    "Envoys meet for second round of ceasefire talks",
    -8 * hour,
  );
  const aTalks2 = art(
    "s-meridian-wire",
    "Meridian Wire",
    "Ceasefire talks resume in Nerath",
    -8 * hour,
  );
  const aTalks3 = art(
    "s-continental",
    "The Continental Observer",
    "Cautious optimism as Nerath talks continue",
    -6 * hour,
  );
  const aSanctions1 = art(
    "s-meridian-wire",
    "Meridian Wire",
    "New sanctions package announced against Velmar entities",
    -50 * hour,
  );
  const aSanctions2 = art(
    "s-continental",
    "The Continental Observer",
    "What the new sanctions cover",
    -48 * hour,
  );
  const aFlood1 = art(
    "s-irc",
    "International Relief Coalition",
    "Situation report: Sundara floods displace thousands",
    -3 * day,
  );
  const aFlood2 = art(
    "s-meridian-wire",
    "Meridian Wire",
    "Relief effort expands in southern Sundara",
    -2 * day,
  );
  const aAddress = art(
    "s-united-assembly",
    "United Assembly Press",
    "Secretary-General remarks on the Meridian crisis",
    -1 * day,
  );
  const aRetracted = art(
    "s-koris-daily",
    "Koris Daily Post",
    "Report of bridge explosion in Nerath (retracted)",
    -4 * day,
  );
  const aArchived1 = art(
    "s-meridian-wire",
    "Meridian Wire",
    "Strike damages depot in Kessel south (archived)",
    -20 * day,
  );
  const aArchived2 = art(
    "s-continental",
    "The Continental Observer",
    "Depot fire followed reported strike (archived)",
    -20 * day,
  );
  const aEmbargo = art(
    "s-meridian-wire",
    "Meridian Wire",
    "Initial reports of new strikes in Kessel east",
    -30 * min,
  );

  const articles = [
    aKesselWire, aKesselObserver, aKesselSynd, aKesselMod, aKesselDenial, aKesselAgg,
    aDrone, aGround1, aGround2, aNaval, aExplosion,
    aIntercept1, aIntercept2, aIntercept3,
    aUnrest1, aUnrest2, aCyber, aTalks1, aTalks2, aTalks3,
    aSanctions1, aSanctions2, aFlood1, aFlood2, aAddress,
    aRetracted, aArchived1, aArchived2, aEmbargo,
  ];

  let claimSeq = 0;
  function claim(
    articleId: string,
    incidentId: string,
    text: string,
    excerpt: string,
    kind: Claim["kind"] = "fact-report",
  ): Claim {
    return {
      id: `clm-${++claimSeq}`,
      articleId,
      incidentId,
      text,
      excerpt,
      passageLocator: `p${claimSeq}-${articleId}`,
      kind,
    };
  }

  const claims: Claim[] = [
    claim(aKesselWire.id, "inc-kessel-strike",
      "Multiple strikes hit Northern Kessel Province overnight.",
      "Residents described a series of loud blasts across the province shortly after midnight."),
    claim(aKesselObserver.id, "inc-kessel-strike",
      "Explosions were heard across several districts of Northern Kessel.",
      "Witnesses in three districts reported explosions within a twenty-minute window."),
    claim(aKesselMod.id, "inc-kessel-strike",
      "Ardenia's defense ministry said it struck military infrastructure.",
      "The ministry said the operation targeted military infrastructure in the Kessel sector.",
      "official-claim"),
    claim(aKesselDenial.id, "inc-kessel-strike",
      "Velmar's government disputed the reported casualty figures.",
      "A spokesperson called the circulating casualty figures inaccurate and premature.",
      "denial"),
    claim(aKesselWire.id, "inc-kessel-strike",
      "A regional health office reported 12–18 people injured.",
      "The provincial health office said between 12 and 18 people were treated for injuries.",
      "casualty-estimate"),
    claim(aDrone.id, "inc-drone-havren",
      "Drone activity was reported near Port Havren.",
      "Port authorities suspended operations for two hours citing reported drone activity."),
    claim(aIntercept1.id, "inc-interception-capital",
      "Air-defense systems engaged targets over the capital region.",
      "Sirens sounded as air-defense batteries engaged what officials described as incoming objects."),
    claim(aIntercept3.id, "inc-interception-capital",
      "Ardenia's military said all incoming objects were intercepted.",
      "The ministry said all objects were intercepted with no ground impact reported.",
      "official-claim"),
    claim(aTalks1.id, "inc-ceasefire-talks",
      "A second round of ceasefire talks convened in Nerath.",
      "Envoys from both delegations met for a second consecutive day of talks."),
    claim(aFlood1.id, "inc-sundara-flood",
      "Flooding has displaced an estimated 40,000 people in southern Sundara.",
      "The coalition estimates roughly 40,000 people displaced across three coastal districts.",
      "casualty-estimate"),
  ];

  // -------------------------------------------------------------------------
  // Incidents. `independentSourceCount`, `verification`, and `confidence`
  // are recomputed by the store pipeline from the article/source graph —
  // values here are placeholders overwritten at build time.
  // -------------------------------------------------------------------------

  function baseEmbargo(firstReportedOffsetMs: number, reason = "Standard kinetic safety delay"): Incident["embargo"] {
    return {
      publishNotBefore: iso(now, firstReportedOffsetMs + 60 * min),
      extendedByEditor: false,
      reason,
    };
  }

  const incidents: Incident[] = [
    {
      id: "inc-kessel-strike",
      headline: "Strikes reported in Northern Kessel Province",
      summary:
        "Multiple strikes were reported across Northern Kessel Province overnight. Ardenia's defense ministry said it targeted military infrastructure; Velmar disputes the reported casualty figures.",
      category: "air-missile-strike",
      conflictId: "cf-ardenia-velmar",
      tags: ["Kessel", "Ardenia–Velmar"],
      eventTime: iso(now, -27 * hour),
      eventTimePrecision: "hour",
      eventTimezone: "Europe/Bucharest",
      firstReportedAt: iso(now, -26 * hour),
      publishedAt: iso(now, -24 * hour),
      updatedAt: iso(now, -20 * hour),
      verification: "corroborated",
      maturity: "stable",
      provenance: {
        officialClaimPresent: true,
        officialClaimSource: "Ardenia Ministry of Defense",
      },
      dispute: "disputed",
      lifecycle: "corrected",
      confidence: { band: "high", rationale: "", version: "" },
      location: {
        name: "Northern Kessel Province",
        countryCode: "XV",
        precision: "admin-region",
        lat: 47.26,
        lon: 29.13,
        uncertaintyKm: 35,
        explanation:
          "Reports name the province but not specific sites; location generalized to the provincial centroid.",
      },
      confirmedFacts: [
        "Multiple explosions occurred in Northern Kessel Province overnight (multiple independent witnesses and outlets).",
        "The provincial health office reported treating people for injuries.",
      ],
      attributedClaims: [
        "Ardenia's defense ministry said the operation struck military infrastructure.",
        "Velmar's government said circulating casualty figures are inaccurate.",
      ],
      disputedPoints: [
        "The number of people injured is disputed between the provincial health office and Velmar's national government.",
      ],
      unknowns: [
        "What was struck has not been independently verified.",
        "Whether there was damage beyond the reported sites is unknown.",
      ],
      casualtyEstimates: [
        { attributedTo: "Kessel provincial health office", text: "12–18 injured (initial estimate)" },
        { attributedTo: "Velmar Government Press Office", text: "Disputes the range; no alternative figure released" },
      ],
      claimIds: [],
      independentSourceCount: 0,
      relatedIncidentIds: ["inc-interception-capital", "inc-ceasefire-talks"],
      briefingId: "brf-sunrise",
      embargo: baseEmbargo(-26 * hour),
      riskWithheld: false,
      updatesLog: [
        { at: iso(now, -24 * hour), text: "Published after safety delay with province-level location." },
        { at: iso(now, -20 * hour), text: "Correction: injury estimate range revised after health-office update." },
      ],
      corrections: [
        {
          at: iso(now, -20 * hour),
          summary:
            "An earlier version cited 20+ injuries from a single report; the sourced range is 12–18.",
        },
      ],
      sensitiveContent: false,
      demo: true,
    },
    {
      id: "inc-drone-havren",
      headline: "Drone activity reported near Port Havren",
      summary:
        "Port authorities suspended operations after reported drone activity. No damage has been reported; details remain limited.",
      category: "drone-event",
      conflictId: "cf-ardenia-velmar",
      tags: ["Port Havren"],
      eventTime: iso(now, -8 * hour),
      eventTimePrecision: "part-of-day",
      eventTimezone: "Europe/Bucharest",
      firstReportedAt: iso(now, -7 * hour),
      publishedAt: iso(now, -5 * hour),
      updatedAt: iso(now, -5 * hour),
      verification: "single-source",
      maturity: "developing",
      provenance: { officialClaimPresent: false },
      dispute: "undisputed",
      lifecycle: "published",
      confidence: { band: "moderate", rationale: "", version: "" },
      location: {
        name: "Port Havren district",
        countryCode: "XA",
        precision: "district",
        lat: 46.5,
        lon: 30.7,
        uncertaintyKm: 20,
        explanation:
          "Only the port district is named in reporting; generalized to the district centroid.",
      },
      confirmedFacts: ["Port operations were suspended for roughly two hours."],
      attributedClaims: ["Port authorities cited reported drone activity as the reason."],
      disputedPoints: [],
      unknowns: ["The number and origin of any drones is unreported.", "No damage assessment has been published."],
      casualtyEstimates: [],
      claimIds: [],
      independentSourceCount: 0,
      relatedIncidentIds: ["inc-kessel-strike"],
      embargo: baseEmbargo(-7 * hour),
      riskWithheld: false,
      updatesLog: [{ at: iso(now, -5 * hour), text: "Published after safety delay." }],
      corrections: [],
      sensitiveContent: false,
      demo: true,
    },
    {
      id: "inc-ground-northline",
      headline: "Fighting reported along northern contact line",
      summary:
        "Two outlets report renewed shelling exchanges along the northern contact line. Extent and casualties are unclear.",
      category: "ground-fighting",
      conflictId: "cf-ardenia-velmar",
      tags: ["contact line"],
      eventTime: iso(now, -12 * hour),
      eventTimePrecision: "part-of-day",
      eventTimezone: "Europe/Bucharest",
      firstReportedAt: iso(now, -11 * hour),
      publishedAt: iso(now, -9 * hour),
      updatedAt: iso(now, -9 * hour),
      verification: "corroborated",
      maturity: "developing",
      provenance: { officialClaimPresent: false },
      dispute: "disputed",
      lifecycle: "published",
      confidence: { band: "moderate", rationale: "", version: "" },
      location: {
        name: "Northern border region",
        countryCode: "XV",
        precision: "admin-region",
        lat: 48.1,
        lon: 31.4,
        uncertaintyKm: 50,
        explanation:
          "Reports reference a broad border region; shown at region level with a wide uncertainty radius.",
      },
      confirmedFacts: ["Shelling was reported by residents on both sides of the border region."],
      attributedClaims: ["Each side attributes the escalation to the other."],
      disputedPoints: ["Which side initiated the exchange is disputed."],
      unknowns: ["Casualty and damage information is not yet reported."],
      casualtyEstimates: [],
      claimIds: [],
      independentSourceCount: 0,
      relatedIncidentIds: ["inc-kessel-strike"],
      embargo: baseEmbargo(-11 * hour),
      riskWithheld: false,
      updatesLog: [{ at: iso(now, -9 * hour), text: "Published after safety delay." }],
      corrections: [],
      sensitiveContent: false,
      demo: true,
    },
    {
      id: "inc-aris-strait",
      headline: "Cargo vessel reports incident in Aris Strait",
      summary:
        "A cargo vessel reported an incident while transiting the Aris Strait. A single outlet has reported the event; no authority has confirmed it.",
      category: "naval-incident",
      conflictId: "cf-ardenia-velmar",
      tags: ["Aris Strait", "shipping"],
      eventTime: iso(now, -16 * hour),
      eventTimePrecision: "hour",
      eventTimezone: "Asia/Dubai",
      firstReportedAt: iso(now, -15 * hour),
      publishedAt: iso(now, -13 * hour),
      updatedAt: iso(now, -13 * hour),
      verification: "single-source",
      maturity: "developing",
      provenance: { officialClaimPresent: false },
      dispute: "undisputed",
      lifecycle: "published",
      confidence: { band: "low", rationale: "", version: "" },
      location: {
        name: "Aris Strait (international waters)",
        countryCode: "XV",
        precision: "coarse-cell",
        lat: 26.7,
        lon: 56.3,
        uncertaintyKm: 60,
        explanation:
          "Maritime incident generalized to a coarse cell of the strait; precise position withheld by policy.",
      },
      confirmedFacts: [],
      attributedClaims: ["The vessel's operator reported an incident to maritime authorities."],
      disputedPoints: [],
      unknowns: ["The nature of the incident is unconfirmed.", "No independent corroboration yet."],
      casualtyEstimates: [],
      claimIds: [],
      independentSourceCount: 0,
      relatedIncidentIds: [],
      embargo: baseEmbargo(-15 * hour),
      riskWithheld: false,
      updatesLog: [{ at: iso(now, -13 * hour), text: "Published after safety delay." }],
      corrections: [],
      sensitiveContent: false,
      demo: true,
    },
    {
      id: "inc-velmar-explosion",
      headline: "Explosion reported in Velmar City industrial zone",
      summary:
        "An explosion was reported in an industrial zone of Velmar City. The cause is unknown and no party has made a claim.",
      category: "explosion",
      tags: ["Velmar City"],
      eventTime: iso(now, -10 * hour),
      eventTimePrecision: "hour",
      eventTimezone: "Europe/Bucharest",
      firstReportedAt: iso(now, -9 * hour),
      publishedAt: iso(now, -7 * hour),
      updatedAt: iso(now, -7 * hour),
      verification: "unverified",
      maturity: "developing",
      provenance: { officialClaimPresent: false },
      dispute: "undisputed",
      lifecycle: "published",
      confidence: { band: "low", rationale: "", version: "" },
      location: {
        name: "Velmar City (city level)",
        countryCode: "XV",
        precision: "city",
        lat: 49.0,
        lon: 32.1,
        uncertaintyKm: 15,
        explanation: "Generalized to city level; the specific site is unverified.",
      },
      confirmedFacts: [],
      attributedClaims: ["A local outlet reported an explosion citing residents."],
      disputedPoints: [],
      unknowns: ["Cause, damage, and casualties are all unreported.", "No official statement has been issued."],
      casualtyEstimates: [],
      claimIds: [],
      independentSourceCount: 0,
      relatedIncidentIds: [],
      embargo: baseEmbargo(-9 * hour),
      riskWithheld: false,
      updatesLog: [{ at: iso(now, -7 * hour), text: "Published after safety delay." }],
      corrections: [],
      sensitiveContent: false,
      demo: true,
    },
    {
      id: "inc-interception-capital",
      headline: "Interceptions reported over Ardenia capital region",
      summary:
        "Air-defense systems engaged targets over the capital region. Ardenia's military says all incoming objects were intercepted; two outlets independently report no ground impact.",
      category: "interception",
      conflictId: "cf-ardenia-velmar",
      tags: ["air defense"],
      eventTime: iso(now, -14 * hour),
      eventTimePrecision: "hour",
      eventTimezone: "Europe/Bucharest",
      firstReportedAt: iso(now, -13 * hour),
      publishedAt: iso(now, -11 * hour),
      updatedAt: iso(now, -11 * hour),
      verification: "corroborated",
      maturity: "stable",
      provenance: {
        officialClaimPresent: true,
        officialClaimSource: "Ardenia Ministry of Defense",
      },
      dispute: "undisputed",
      lifecycle: "published",
      confidence: { band: "high", rationale: "", version: "" },
      location: {
        name: "Ardenia capital region",
        countryCode: "XA",
        precision: "admin-region",
        lat: 46.9,
        lon: 28.8,
        uncertaintyKm: 30,
        explanation: "Generalized to the capital region; engagement sites are not published.",
      },
      confirmedFacts: [
        "Air-raid sirens sounded across the capital region.",
        "Air-defense engagements were observed by multiple witnesses.",
      ],
      attributedClaims: ["Ardenia's military said all incoming objects were intercepted."],
      disputedPoints: [],
      unknowns: ["The number and type of objects engaged is not independently verified."],
      casualtyEstimates: [],
      claimIds: [],
      independentSourceCount: 0,
      relatedIncidentIds: ["inc-kessel-strike"],
      briefingId: "brf-sunrise",
      embargo: baseEmbargo(-13 * hour),
      riskWithheld: false,
      updatesLog: [{ at: iso(now, -11 * hour), text: "Published after safety delay." }],
      corrections: [],
      sensitiveContent: false,
      demo: true,
    },
    {
      id: "inc-koris-protests",
      headline: "Protests continue in Koris capital for third day",
      summary:
        "Large crowds gathered in the Koris capital for a third consecutive day following disputed election results. Reporting describes the protests as largely peaceful.",
      category: "civil-unrest",
      conflictId: "cf-koris-unrest",
      tags: ["protests", "election"],
      eventTime: iso(now, -30 * hour),
      eventTimePrecision: "day",
      eventTimezone: "Asia/Bangkok",
      firstReportedAt: iso(now, -30 * hour),
      publishedAt: iso(now, -28 * hour),
      updatedAt: iso(now, -26 * hour),
      verification: "corroborated",
      maturity: "stable",
      provenance: { officialClaimPresent: false },
      dispute: "undisputed",
      lifecycle: "published",
      confidence: { band: "moderate", rationale: "", version: "" },
      location: {
        name: "Koris capital (city level)",
        countryCode: "XK",
        precision: "city",
        lat: 13.8,
        lon: 100.5,
        uncertaintyKm: 12,
        explanation: "City-level location; assembly points are not mapped.",
      },
      confirmedFacts: ["Large daytime gatherings occurred on three consecutive days."],
      attributedClaims: ["Organizers say turnout exceeded prior days; authorities have not published estimates."],
      disputedPoints: [],
      unknowns: ["Crowd size estimates vary widely and are unverified."],
      casualtyEstimates: [],
      claimIds: [],
      independentSourceCount: 0,
      relatedIncidentIds: [],
      embargo: {
        publishNotBefore: iso(now, -29 * hour),
        extendedByEditor: false,
        reason: "Non-kinetic; standard review delay",
      },
      riskWithheld: false,
      updatesLog: [{ at: iso(now, -26 * hour), text: "Updated with third-day coverage." }],
      corrections: [],
      sensitiveContent: false,
      demo: true,
    },
    {
      id: "inc-velmar-cyber",
      headline: "Velmar utility reports service disruption",
      summary:
        "A Velmar utility reported a service disruption it attributed to a cyber incident. Attribution is unclear and disputed.",
      category: "cyber-incident",
      conflictId: "cf-ardenia-velmar",
      tags: ["infrastructure", "cyber"],
      eventTime: iso(now, -21 * hour),
      eventTimePrecision: "hour",
      eventTimezone: "Europe/Bucharest",
      firstReportedAt: iso(now, -20 * hour),
      publishedAt: iso(now, -18 * hour),
      updatedAt: iso(now, -18 * hour),
      verification: "single-source",
      maturity: "developing",
      provenance: { officialClaimPresent: false },
      dispute: "disputed",
      lifecycle: "published",
      confidence: { band: "low", rationale: "", version: "" },
      location: {
        name: "Velmar (country level)",
        countryCode: "XV",
        precision: "country",
        lat: 49.4,
        lon: 31.9,
        uncertaintyKm: 150,
        explanation: "Cyber incident shown at country level; facility locations are not mapped.",
      },
      confirmedFacts: ["The utility acknowledged a service disruption."],
      attributedClaims: ["The utility attributed the disruption to a cyber incident."],
      disputedPoints: ["Independent analysts note an unpatched outage could explain the disruption."],
      unknowns: ["No technical indicators have been published.", "No actor has claimed responsibility."],
      casualtyEstimates: [],
      claimIds: [],
      independentSourceCount: 0,
      relatedIncidentIds: [],
      embargo: {
        publishNotBefore: iso(now, -19 * hour),
        extendedByEditor: false,
        reason: "Non-kinetic; standard review delay",
      },
      riskWithheld: false,
      updatesLog: [{ at: iso(now, -18 * hour), text: "Published." }],
      corrections: [],
      sensitiveContent: false,
      demo: true,
    },
    {
      id: "inc-ceasefire-talks",
      headline: "Second round of ceasefire talks convenes in Nerath",
      summary:
        "Envoys from Ardenia and Velmar met for a second round of ceasefire talks hosted in Nerath, with United Assembly mediation.",
      category: "ceasefire-negotiation",
      conflictId: "cf-ardenia-velmar",
      tags: ["diplomacy", "Nerath talks"],
      eventTime: iso(now, -8 * hour),
      eventTimePrecision: "hour",
      eventTimezone: "Europe/Vienna",
      firstReportedAt: iso(now, -8 * hour),
      publishedAt: iso(now, -7 * hour),
      updatedAt: iso(now, -5 * hour),
      verification: "corroborated",
      maturity: "stable",
      provenance: {
        officialClaimPresent: true,
        officialClaimSource: "United Assembly Press",
      },
      dispute: "undisputed",
      lifecycle: "published",
      confidence: { band: "high", rationale: "", version: "" },
      location: {
        name: "Nerath capital (city level)",
        countryCode: "XN",
        precision: "city",
        lat: 48.2,
        lon: 16.4,
        uncertaintyKm: 10,
        explanation: "Publicly announced diplomatic venue, shown at city level.",
      },
      confirmedFacts: [
        "Both delegations attended a second day of talks.",
        "The United Assembly confirmed mediation is ongoing.",
      ],
      attributedClaims: ["Delegation officials described the atmosphere as constructive."],
      disputedPoints: [],
      unknowns: ["No agenda details or draft terms have been published."],
      casualtyEstimates: [],
      claimIds: [],
      independentSourceCount: 0,
      relatedIncidentIds: ["inc-kessel-strike"],
      briefingId: "brf-sunset",
      embargo: {
        publishNotBefore: iso(now, -8 * hour),
        extendedByEditor: false,
        reason: "Publicly announced diplomatic event; no kinetic delay",
      },
      riskWithheld: false,
      updatesLog: [
        { at: iso(now, -7 * hour), text: "Published." },
        { at: iso(now, -5 * hour), text: "Updated: talks extended into the evening." },
      ],
      corrections: [],
      sensitiveContent: false,
      demo: true,
    },
    {
      id: "inc-sanctions-package",
      headline: "New sanctions package announced against Velmar entities",
      summary:
        "A coalition of states announced a sanctions package targeting fictional Velmar entities linked to the conflict.",
      category: "sanctions-diplomacy",
      conflictId: "cf-ardenia-velmar",
      tags: ["sanctions"],
      eventTime: iso(now, -50 * hour),
      eventTimePrecision: "exact",
      eventTimezone: "Europe/Brussels",
      firstReportedAt: iso(now, -50 * hour),
      publishedAt: iso(now, -49 * hour),
      updatedAt: iso(now, -49 * hour),
      verification: "corroborated",
      maturity: "stable",
      provenance: { officialClaimPresent: true, officialClaimSource: "Coalition joint statement" },
      dispute: "undisputed",
      lifecycle: "published",
      confidence: { band: "high", rationale: "", version: "" },
      location: {
        name: "Announced in Brussels-hosted summit (venue city)",
        countryCode: "XN",
        precision: "city",
        lat: 50.8,
        lon: 4.4,
        uncertaintyKm: 10,
        explanation: "Diplomatic announcement mapped to its public venue city.",
      },
      confirmedFacts: ["The joint statement and entity list were published by the coalition."],
      attributedClaims: ["Velmar's foreign ministry called the measures unjustified."],
      disputedPoints: [],
      unknowns: ["Implementation timelines vary by member state."],
      casualtyEstimates: [],
      claimIds: [],
      independentSourceCount: 0,
      relatedIncidentIds: ["inc-ceasefire-talks"],
      embargo: {
        publishNotBefore: iso(now, -50 * hour),
        extendedByEditor: false,
        reason: "Public announcement; no delay required",
      },
      riskWithheld: false,
      updatesLog: [{ at: iso(now, -49 * hour), text: "Published." }],
      corrections: [],
      sensitiveContent: false,
      demo: true,
    },
    {
      id: "inc-sundara-flood",
      headline: "Sundara floods displace an estimated 40,000 people",
      summary:
        "Severe flooding in southern Sundara has displaced an estimated 40,000 people according to relief organizations. Disaster context — unrelated to any conflict.",
      category: "humanitarian-emergency",
      conflictId: "cf-sundara-humanitarian",
      tags: ["floods", "displacement", "disaster-context"],
      eventTime: iso(now, -3 * day),
      eventTimePrecision: "day",
      eventTimezone: "Africa/Bamako",
      firstReportedAt: iso(now, -3 * day),
      publishedAt: iso(now, -3 * day + 2 * hour),
      updatedAt: iso(now, -2 * day),
      verification: "corroborated",
      maturity: "stable",
      provenance: {
        officialClaimPresent: true,
        officialClaimSource: "Sundara National Disaster Agency",
      },
      dispute: "undisputed",
      lifecycle: "published",
      confidence: { band: "high", rationale: "", version: "" },
      location: {
        name: "Southern Sundara coastal districts",
        countryCode: "XS",
        precision: "admin-region",
        lat: 12.6,
        lon: -8.0,
        uncertaintyKm: 80,
        explanation: "Region-level location covering the three affected districts.",
      },
      confirmedFacts: [
        "Three coastal districts are experiencing severe flooding.",
        "Relief distribution has begun in accessible areas.",
      ],
      attributedClaims: [
        "The International Relief Coalition estimates roughly 40,000 people displaced.",
      ],
      disputedPoints: [],
      unknowns: ["Access to two low-lying areas remains limited, so figures may change."],
      casualtyEstimates: [
        { attributedTo: "International Relief Coalition", text: "~40,000 displaced (estimate)" },
      ],
      claimIds: [],
      independentSourceCount: 0,
      relatedIncidentIds: [],
      briefingId: "brf-sunrise",
      embargo: {
        publishNotBefore: iso(now, -3 * day),
        extendedByEditor: false,
        reason: "Humanitarian report; no kinetic delay",
      },
      riskWithheld: false,
      updatesLog: [
        { at: iso(now, -3 * day + 2 * hour), text: "Published from relief-coalition situation report." },
        { at: iso(now, -2 * day), text: "Updated with expanded relief-effort coverage." },
      ],
      corrections: [],
      sensitiveContent: false,
      demo: true,
    },
    {
      id: "inc-ua-remarks",
      headline: "United Assembly Secretary-General addresses the Meridian crisis",
      summary:
        "The Secretary-General delivered public remarks on the Ardenia–Velmar conflict, urging both parties to extend the Nerath talks.",
      category: "official-address",
      conflictId: "cf-ardenia-velmar",
      tags: ["United Assembly", "address"],
      eventTime: iso(now, -1 * day),
      eventTimePrecision: "exact",
      eventTimezone: "America/New_York",
      firstReportedAt: iso(now, -1 * day),
      publishedAt: iso(now, -1 * day + 30 * min),
      updatedAt: iso(now, -1 * day + 30 * min),
      verification: "corroborated",
      maturity: "stable",
      provenance: { officialClaimPresent: true, officialClaimSource: "United Assembly Press" },
      dispute: "undisputed",
      lifecycle: "published",
      confidence: { band: "high", rationale: "", version: "" },
      location: {
        name: "United Assembly headquarters (venue city)",
        countryCode: "XN",
        precision: "city",
        lat: 40.7,
        lon: -74.0,
        uncertaintyKm: 10,
        explanation: "Public speech mapped to its announced venue city.",
      },
      confirmedFacts: ["The remarks were delivered and published in full by the organization."],
      attributedClaims: [],
      disputedPoints: [],
      unknowns: [],
      casualtyEstimates: [],
      claimIds: [],
      independentSourceCount: 0,
      relatedIncidentIds: ["inc-ceasefire-talks"],
      embargo: {
        publishNotBefore: iso(now, -1 * day),
        extendedByEditor: false,
        reason: "Public address; no delay required",
      },
      riskWithheld: false,
      updatesLog: [{ at: iso(now, -1 * day + 30 * min), text: "Published with replay link." }],
      corrections: [],
      sensitiveContent: false,
      demo: true,
    },
    {
      id: "inc-nerath-bridge-retracted",
      headline: "Report of bridge explosion in Nerath — RETRACTED",
      summary:
        "An earlier report of a bridge explosion in Nerath was retracted after the footage was shown to be from an unrelated 2019 demolition.",
      category: "explosion",
      tags: ["retraction"],
      eventTime: iso(now, -4 * day),
      eventTimePrecision: "day",
      eventTimezone: "Europe/Vienna",
      firstReportedAt: iso(now, -4 * day),
      publishedAt: iso(now, -4 * day + 2 * hour),
      updatedAt: iso(now, -3 * day),
      verification: "unverified",
      maturity: "stable",
      provenance: { officialClaimPresent: false },
      dispute: "disputed",
      lifecycle: "retracted",
      confidence: { band: "low", rationale: "", version: "" },
      location: {
        name: "Nerath (country level)",
        countryCode: "XN",
        precision: "country",
        lat: 47.6,
        lon: 15.1,
        uncertaintyKm: 120,
        explanation: "Retracted report retained at country level for the correction record.",
      },
      confirmedFacts: [],
      attributedClaims: [],
      disputedPoints: ["The originating footage was misattributed."],
      unknowns: [],
      casualtyEstimates: [],
      claimIds: [],
      independentSourceCount: 0,
      relatedIncidentIds: [],
      embargo: baseEmbargo(-4 * day),
      riskWithheld: false,
      updatesLog: [
        { at: iso(now, -4 * day + 2 * hour), text: "Published from a single local report." },
        { at: iso(now, -3 * day), text: "Retracted: footage identified as a 2019 demolition." },
      ],
      corrections: [
        {
          at: iso(now, -3 * day),
          summary:
            "Retraction: the event did not occur. The source video was from an unrelated 2019 controlled demolition.",
        },
      ],
      sensitiveContent: false,
      demo: true,
    },
    {
      id: "inc-kessel-depot-archived",
      headline: "Strike damaged storage depot in southern Kessel (archived)",
      summary:
        "A strike three weeks ago damaged a storage depot in southern Kessel. The incident is archived; no further updates are expected.",
      category: "air-missile-strike",
      conflictId: "cf-ardenia-velmar",
      tags: ["Kessel", "archived"],
      eventTime: iso(now, -20 * day),
      eventTimePrecision: "day",
      eventTimezone: "Europe/Bucharest",
      firstReportedAt: iso(now, -20 * day),
      publishedAt: iso(now, -20 * day + 3 * hour),
      updatedAt: iso(now, -18 * day),
      verification: "corroborated",
      maturity: "stable",
      provenance: { officialClaimPresent: false },
      dispute: "undisputed",
      lifecycle: "archived",
      confidence: { band: "moderate", rationale: "", version: "" },
      location: {
        name: "Southern Kessel Province",
        countryCode: "XV",
        precision: "admin-region",
        lat: 46.6,
        lon: 29.6,
        uncertaintyKm: 40,
        explanation:
          "Historical incident kept at province level after editorial review; finer geometry suppressed as unnecessary.",
      },
      confirmedFacts: ["A depot fire followed the reported strike (two independent outlets)."],
      attributedClaims: [],
      disputedPoints: [],
      unknowns: [],
      casualtyEstimates: [],
      claimIds: [],
      independentSourceCount: 0,
      relatedIncidentIds: ["inc-kessel-strike"],
      embargo: baseEmbargo(-20 * day),
      riskWithheld: false,
      updatesLog: [
        { at: iso(now, -20 * day + 3 * hour), text: "Published after safety delay." },
        { at: iso(now, -18 * day), text: "Archived." },
      ],
      corrections: [],
      sensitiveContent: false,
      demo: true,
    },
    // Embargoed: first reported 30 min ago; kinetic delay has NOT elapsed.
    // Must never be returned by any public endpoint until it has.
    {
      id: "inc-kessel-east-embargoed",
      headline: "Initial reports of new strikes in eastern Kessel",
      summary: "Early, unconfirmed reports of strikes in eastern Kessel.",
      category: "air-missile-strike",
      conflictId: "cf-ardenia-velmar",
      tags: ["Kessel"],
      eventTime: iso(now, -40 * min),
      eventTimePrecision: "hour",
      eventTimezone: "Europe/Bucharest",
      firstReportedAt: iso(now, -30 * min),
      publishedAt: iso(now, 30 * min),
      updatedAt: iso(now, -20 * min),
      verification: "single-source",
      maturity: "developing",
      provenance: { officialClaimPresent: false },
      dispute: "undisputed",
      lifecycle: "published",
      confidence: { band: "low", rationale: "", version: "" },
      location: {
        name: "Eastern Kessel Province",
        countryCode: "XV",
        precision: "admin-region",
        lat: 47.4,
        lon: 30.2,
        uncertaintyKm: 40,
        explanation: "Province-level only.",
      },
      confirmedFacts: [],
      attributedClaims: ["A wire service relayed initial local reports."],
      disputedPoints: [],
      unknowns: ["Everything beyond initial reports."],
      casualtyEstimates: [],
      claimIds: [],
      independentSourceCount: 0,
      relatedIncidentIds: [],
      embargo: {
        publishNotBefore: iso(now, 30 * min),
        extendedByEditor: false,
        reason: "Standard 60-minute kinetic safety delay from first report",
      },
      riskWithheld: false,
      updatesLog: [],
      corrections: [],
      sensitiveContent: false,
      demo: true,
    },
    // Risk-withheld: embargo time has passed but the server-side risk gate
    // continues to withhold. Must never be returned publicly.
    {
      id: "inc-risk-withheld",
      headline: "Reported drone activity near an evacuation corridor",
      summary: "Withheld pending editorial risk review.",
      category: "drone-event",
      conflictId: "cf-ardenia-velmar",
      tags: [],
      eventTime: iso(now, -5 * hour),
      eventTimePrecision: "hour",
      eventTimezone: "Europe/Bucharest",
      firstReportedAt: iso(now, -5 * hour),
      publishedAt: iso(now, -3 * hour),
      updatedAt: iso(now, -3 * hour),
      verification: "single-source",
      maturity: "developing",
      provenance: { officialClaimPresent: false },
      dispute: "undisputed",
      lifecycle: "published",
      confidence: { band: "low", rationale: "", version: "" },
      location: {
        name: "Withheld",
        countryCode: "XV",
        precision: "country",
        lat: 49.4,
        lon: 31.9,
        uncertaintyKm: 150,
        explanation: "Withheld.",
      },
      confirmedFacts: [],
      attributedClaims: [],
      disputedPoints: [],
      unknowns: [],
      casualtyEstimates: [],
      claimIds: [],
      independentSourceCount: 0,
      relatedIncidentIds: [],
      embargo: baseEmbargo(-5 * hour),
      riskWithheld: true,
      riskWithheldReason:
        "Could reveal details of an ongoing civilian evacuation; withheld until the operation concludes.",
      updatesLog: [],
      corrections: [],
      sensitiveContent: true,
      demo: true,
    },
  ];

  // Attach claims to incidents.
  for (const inc of incidents) {
    inc.claimIds = claims.filter((c) => c.incidentId === inc.id).map((c) => c.id);
  }

  const articleIdsByIncident: Record<string, string[]> = {
    "inc-kessel-strike": [
      aKesselWire.id, aKesselObserver.id, aKesselSynd.id,
      aKesselMod.id, aKesselDenial.id, aKesselAgg.id,
    ],
    "inc-drone-havren": [aDrone.id],
    "inc-ground-northline": [aGround1.id, aGround2.id],
    "inc-aris-strait": [aNaval.id],
    "inc-velmar-explosion": [aExplosion.id],
    "inc-interception-capital": [aIntercept1.id, aIntercept2.id, aIntercept3.id],
    "inc-koris-protests": [aUnrest1.id, aUnrest2.id],
    "inc-velmar-cyber": [aCyber.id],
    "inc-ceasefire-talks": [aTalks1.id, aTalks2.id, aTalks3.id],
    "inc-sanctions-package": [aSanctions1.id, aSanctions2.id],
    "inc-sundara-flood": [aFlood1.id, aFlood2.id],
    "inc-ua-remarks": [aAddress.id],
    "inc-nerath-bridge-retracted": [aRetracted.id],
    "inc-kessel-depot-archived": [aArchived1.id, aArchived2.id],
    "inc-kessel-east-embargoed": [aEmbargo.id],
    "inc-risk-withheld": [],
  };

  const newsClusters: NewsCluster[] = [
    {
      id: "news-kessel-strike",
      headline: "Strikes reported across Northern Kessel Province",
      summary: "Two independent outlets corroborate overnight strikes; casualty figures remain disputed.",
      region: "Western Meridian",
      countryCode: "XV",
      category: "conflict",
      badge: "breaking",
      eventTime: iso(now, -27 * hour),
      publishedAt: iso(now, -26 * hour),
      leadPublisher: "Meridian Wire",
      articleIds: articleIdsByIncident["inc-kessel-strike"],
      independentSourceCount: 2,
      verification: "corroborated",
      maturity: "stable",
      dispute: "disputed",
      lifecycle: "corrected",
      confidence: { band: "high", rationale: "Corroborated by two independent outlets with official claims tracked separately.", version: "2026.07-1" },
      relatedIncidentId: "inc-kessel-strike",
      significance: 88,
      significanceFactors: [
        "Corroborated kinetic event in an active conflict",
        "Casualty reports present",
        "Official statements from both parties",
      ],
      demo: true,
    },
    {
      id: "news-talks",
      headline: "Ceasefire talks extended into the evening in Nerath",
      summary: "Mediators said discussions were constructive and will continue tomorrow.",
      region: "Western Meridian",
      countryCode: "XN",
      category: "diplomacy",
      badge: null,
      eventTime: iso(now, -6 * hour),
      publishedAt: iso(now, -6 * hour),
      leadPublisher: "United Assembly Press",
      articleIds: [aTalks1.id, aTalks2.id, aTalks3.id],
      independentSourceCount: 3,
      verification: "corroborated",
      maturity: "stable",
      dispute: "undisputed",
      lifecycle: "published",
      confidence: { band: "high", rationale: "Publicly confirmed diplomatic event with three independent reports.", version: "2026.07-1" },
      relatedIncidentId: "inc-ceasefire-talks",
      significance: 75,
      significanceFactors: ["Active mediation in a major conflict", "Multiple independent confirmations"],
      demo: true,
    },
    {
      id: "news-flood",
      headline: "Relief effort expands as Sundara flood displacement grows",
      summary: "The International Relief Coalition estimates ~40,000 displaced across three districts.",
      region: "Sahel Coast",
      countryCode: "XS",
      category: "humanitarian",
      badge: null,
      eventTime: iso(now, -2 * day),
      publishedAt: iso(now, -2 * day),
      leadPublisher: "International Relief Coalition",
      articleIds: [aFlood1.id, aFlood2.id],
      independentSourceCount: 2,
      verification: "corroborated",
      maturity: "stable",
      dispute: "undisputed",
      lifecycle: "published",
      confidence: { band: "high", rationale: "Relief-organization reporting corroborated by wire coverage.", version: "2026.07-1" },
      relatedIncidentId: "inc-sundara-flood",
      significance: 70,
      significanceFactors: ["Large-scale displacement", "Ongoing humanitarian response"],
      demo: true,
    },
    {
      id: "news-ua-remarks",
      headline: "Secretary-General urges parties to extend Nerath talks",
      summary: "Full remarks and replay published by the United Assembly.",
      region: "Global",
      category: "official",
      badge: "official-statement",
      eventTime: iso(now, -1 * day),
      publishedAt: iso(now, -1 * day),
      leadPublisher: "United Assembly Press",
      articleIds: [aAddress.id],
      independentSourceCount: 1,
      verification: "single-source",
      maturity: "stable",
      dispute: "undisputed",
      lifecycle: "published",
      confidence: { band: "high", rationale: "Primary-source publication of the organization's own remarks.", version: "2026.07-1" },
      relatedIncidentId: "inc-ua-remarks",
      significance: 65,
      significanceFactors: ["Head of a major international organization", "Directly addresses active mediation"],
      demo: true,
    },
    {
      id: "news-drone-havren",
      headline: "Port Havren suspends operations after reported drone activity",
      summary: "A single wire report so far; no damage reported.",
      region: "Western Meridian",
      countryCode: "XA",
      category: "conflict",
      badge: "breaking",
      eventTime: iso(now, -8 * hour),
      publishedAt: iso(now, -7 * hour),
      leadPublisher: "Meridian Wire",
      articleIds: [aDrone.id],
      independentSourceCount: 1,
      verification: "single-source",
      maturity: "developing",
      dispute: "undisputed",
      lifecycle: "published",
      confidence: { band: "moderate", rationale: "Single reliable source; operational suspension confirmed by port notice.", version: "2026.07-1" },
      relatedIncidentId: "inc-drone-havren",
      significance: 55,
      significanceFactors: ["Port disruption", "Developing"],
      demo: true,
    },
    {
      id: "news-sanctions",
      headline: "Coalition announces sanctions on Velmar-linked entities",
      summary: "The package lists entities tied to the fictional conflict; implementation varies by state.",
      region: "Western Meridian",
      category: "diplomacy",
      badge: "analysis",
      eventTime: iso(now, -50 * hour),
      publishedAt: iso(now, -48 * hour),
      leadPublisher: "The Continental Observer",
      articleIds: [aSanctions1.id, aSanctions2.id],
      independentSourceCount: 2,
      verification: "corroborated",
      maturity: "stable",
      dispute: "undisputed",
      lifecycle: "published",
      confidence: { band: "high", rationale: "Official publication corroborated by independent coverage.", version: "2026.07-1" },
      relatedIncidentId: "inc-sanctions-package",
      significance: 60,
      significanceFactors: ["Multilateral policy action"],
      demo: true,
    },
    {
      id: "news-koris",
      headline: "Koris protests enter third day after disputed vote",
      summary: "Crowds remain large and largely peaceful, correspondents report.",
      region: "Eastern Sund Basin",
      countryCode: "XK",
      category: "conflict",
      badge: null,
      eventTime: iso(now, -30 * hour),
      publishedAt: iso(now, -29 * hour),
      leadPublisher: "Koris Daily Post",
      articleIds: [aUnrest1.id, aUnrest2.id],
      independentSourceCount: 2,
      verification: "corroborated",
      maturity: "stable",
      dispute: "undisputed",
      lifecycle: "published",
      confidence: { band: "moderate", rationale: "Two independent outlets; crowd sizes unverified.", version: "2026.07-1" },
      relatedIncidentId: "inc-koris-protests",
      significance: 50,
      significanceFactors: ["Sustained nationwide unrest"],
      demo: true,
    },
    {
      id: "news-retraction",
      headline: "RETRACTED: Nerath bridge explosion report",
      summary: "The footage behind the report was from an unrelated 2019 demolition. The report has been withdrawn.",
      region: "Western Meridian",
      countryCode: "XN",
      category: "conflict",
      badge: null,
      publishedAt: iso(now, -3 * day),
      leadPublisher: "Koris Daily Post",
      articleIds: [aRetracted.id],
      independentSourceCount: 0,
      verification: "unverified",
      maturity: "stable",
      dispute: "disputed",
      lifecycle: "retracted",
      confidence: { band: "low", rationale: "Retracted after the source footage was identified as unrelated archive video.", version: "2026.07-1" },
      relatedIncidentId: "inc-nerath-bridge-retracted",
      significance: 30,
      significanceFactors: ["Correction record"],
      demo: true,
    },
  ];

  const addresses: OfficialAddress[] = [
    {
      id: "addr-ardenia-pm",
      title: "Address to the nation on the security situation",
      speaker: "Prime Minister Elen Maros",
      office: "Prime Minister",
      countryOrOrg: "Ardenia",
      topic: "Security situation and the Nerath talks",
      originalLanguage: "en",
      scheduledAtUtc: iso(now, 3 * hour),
      state: "upcoming",
      officialSourceName: "Office of the Prime Minister of Ardenia",
      officialSourceUrl: "https://pm.ardenia.example/live",
      keyAnnouncements: [],
      citedIncidentIds: [],
      demo: true,
    },
    {
      id: "addr-velmar-briefing",
      title: "Defense ministry press briefing",
      speaker: "Spokesperson Col. D. Verek",
      office: "Ministry of Defense",
      countryOrOrg: "Velmar",
      topic: "Daily operational statement",
      originalLanguage: "en",
      scheduledAtUtc: iso(now, -20 * min),
      durationMinutes: 45,
      state: "live",
      officialSourceName: "Velmar Ministry of Defense",
      officialSourceUrl: "https://mod.velmar.example/briefings/today",
      keyAnnouncements: [],
      citedIncidentIds: ["inc-kessel-strike"],
      demo: true,
    },
    {
      id: "addr-ua-sg",
      title: "Secretary-General remarks on the Meridian crisis",
      speaker: "Secretary-General Amara Diehl",
      office: "Secretary-General",
      countryOrOrg: "United Assembly",
      topic: "Meridian crisis and mediation",
      originalLanguage: "en",
      scheduledAtUtc: iso(now, -1 * day),
      durationMinutes: 18,
      state: "replay-available",
      officialSourceName: "United Assembly Press",
      officialSourceUrl: "https://press.unitedassembly.example/replays/sg-meridian",
      embeddablePlayerUrl: undefined,
      transcript: [
        { atSeconds: 0, speaker: "Secretary-General Diehl", text: "Thank you. I will speak briefly about the situation in the Meridian region." },
        { atSeconds: 42, speaker: "Secretary-General Diehl", text: "The talks in Nerath represent the most credible path to a durable ceasefire." },
        { atSeconds: 120, speaker: "Secretary-General Diehl", text: "I urge both parties to extend the current round and to protect civilian infrastructure without condition." },
        { atSeconds: 300, speaker: "Secretary-General Diehl", text: "Humanitarian access must not be used as a bargaining position. Thank you." },
      ],
      translatedSummary:
        "The Secretary-General urged Ardenia and Velmar to extend the Nerath talks, called for unconditional protection of civilian infrastructure, and said humanitarian access must not be a bargaining position.",
      keyAnnouncements: [
        "Urged extension of the Nerath ceasefire talks",
        "Called for protection of civilian infrastructure without condition",
      ],
      citedIncidentIds: ["inc-ceasefire-talks", "inc-kessel-strike"],
      demo: true,
    },
    {
      id: "addr-koris-pressconf",
      title: "Electoral commission press conference",
      speaker: "Commission Chair R. Anand",
      office: "National Electoral Commission",
      countryOrOrg: "Koris",
      topic: "Election results review — CANCELLED",
      originalLanguage: "en",
      scheduledAtUtc: iso(now, -6 * hour),
      state: "cancelled",
      officialSourceName: "Koris National Electoral Commission",
      officialSourceUrl: "https://nec.koris.example/press",
      keyAnnouncements: [],
      citedIncidentIds: ["inc-koris-protests"],
      demo: true,
    },
    {
      id: "addr-mto-statement",
      title: "Meridian Treaty Organization ministerial statement",
      speaker: "Secretary Delegate H. Okafor",
      office: "Secretariat",
      countryOrOrg: "Meridian Treaty Organization",
      topic: "Ministerial statement on regional security",
      originalLanguage: "en",
      scheduledAtUtc: iso(now, -2 * day),
      durationMinutes: 25,
      state: "replay-unavailable",
      officialSourceName: "MTO Secretariat",
      officialSourceUrl: "https://mto.example/statements/ministerial",
      keyAnnouncements: ["Reaffirmed support for the Nerath mediation track"],
      citedIncidentIds: ["inc-ceasefire-talks"],
      demo: true,
    },
  ];

  const briefings: Briefing[] = [
    {
      id: "brf-sunrise",
      kind: "sunrise",
      title: "Sunrise Brief",
      coverageWindowStart: iso(now, -18 * hour),
      coverageWindowEnd: iso(now, -6 * hour),
      publishedAt: iso(now, -5 * hour),
      updatedAt: iso(now, -5 * hour),
      authoringMethod: "AI-assisted draft with claim-level source lineage; reviewed and approved by an editor.",
      summary60s:
        "Overnight, strikes were reported in Northern Kessel Province with disputed injury figures, and air defenses were active over Ardenia's capital region. Ceasefire talks in Nerath continue into a second day with cautious optimism from mediators. In Sundara, flood displacement estimates remain around 40,000 as relief expands. Watch today: a scheduled address by Ardenia's prime minister and the possible extension of the Nerath talks.",
      topDevelopments: [
        { text: "Strikes reported across Northern Kessel Province; injury figures disputed.", sourceArticleIds: [aKesselWire.id, aKesselObserver.id] },
        { text: "Interceptions reported over Ardenia's capital region with no confirmed ground impact.", sourceArticleIds: [aIntercept1.id, aIntercept2.id] },
        { text: "Nerath ceasefire talks entered a second day.", sourceArticleIds: [aTalks1.id, aTalks2.id] },
      ],
      changedSincePrior: [
        { text: "The Kessel injury estimate was corrected to a sourced 12–18 range.", sourceArticleIds: [aKesselWire.id] },
      ],
      majorIncidentIds: ["inc-kessel-strike", "inc-interception-capital", "inc-sundara-flood"],
      diplomaticDevelopments: [
        { text: "Mediators described the Nerath talks as constructive and ongoing.", sourceArticleIds: [aTalks1.id, aTalks3.id] },
      ],
      humanitarianImpact: [
        { text: "Roughly 40,000 people are estimated displaced by Sundara flooding.", sourceArticleIds: [aFlood1.id] },
      ],
      conflictingReports: [
        { text: "Velmar's government disputes the Kessel injury figures; the provincial health office stands by its range.", sourceArticleIds: [aKesselDenial.id, aKesselWire.id] },
      ],
      whatToWatch: [
        { text: "Ardenia's prime minister is scheduled to address the nation today (publicly announced).", sourceArticleIds: [aAddress.id] },
        { text: "Mediators may announce whether the Nerath talks extend a third day.", sourceArticleIds: [aTalks3.id] },
      ],
      corrections: [],
      demo: true,
    },
    {
      id: "brf-sunset",
      kind: "sunset",
      title: "Sunset Brief",
      coverageWindowStart: iso(now, -30 * hour),
      coverageWindowEnd: iso(now, -18 * hour),
      publishedAt: iso(now, -17 * hour),
      updatedAt: iso(now, -15 * hour),
      authoringMethod: "AI-assisted draft with claim-level source lineage; reviewed and approved by an editor.",
      summary60s:
        "Yesterday evening's picture: ceasefire talks resumed in Nerath under United Assembly mediation, Koris protests continued for a third day, and a Velmar utility reported a disputed cyber incident. A sanctions package against Velmar-linked entities moved into implementation.",
      topDevelopments: [
        { text: "Ceasefire talks resumed in Nerath.", sourceArticleIds: [aTalks2.id] },
        { text: "Koris protests continued for a third consecutive day.", sourceArticleIds: [aUnrest1.id, aUnrest2.id] },
      ],
      changedSincePrior: [
        { text: "The Nerath bridge explosion report was retracted after footage was identified as archive video.", sourceArticleIds: [aRetracted.id] },
      ],
      majorIncidentIds: ["inc-ceasefire-talks", "inc-koris-protests", "inc-velmar-cyber"],
      diplomaticDevelopments: [
        { text: "Sanctions implementation timelines were published by several coalition members.", sourceArticleIds: [aSanctions2.id] },
      ],
      humanitarianImpact: [
        { text: "Relief distribution expanded in accessible districts of southern Sundara.", sourceArticleIds: [aFlood2.id] },
      ],
      conflictingReports: [
        { text: "The cause of the Velmar utility disruption is contested: the utility cites a cyber incident; independent analysts note an outage could explain it.", sourceArticleIds: [aCyber.id] },
      ],
      whatToWatch: [
        { text: "The United Assembly Secretary-General is scheduled to speak on the Meridian crisis (publicly announced).", sourceArticleIds: [aAddress.id] },
      ],
      corrections: [
        { at: iso(now, -15 * hour), summary: "Added the bridge-report retraction to 'changed since prior'." },
      ],
      demo: true,
    },
    {
      id: "brf-meridian",
      kind: "regional",
      title: "Western Meridian Daily Brief",
      region: "Western Meridian",
      coverageWindowStart: iso(now, -30 * hour),
      coverageWindowEnd: iso(now, -6 * hour),
      publishedAt: iso(now, -4 * hour),
      updatedAt: iso(now, -4 * hour),
      authoringMethod: "AI-assisted draft with claim-level source lineage; reviewed and approved by an editor.",
      summary60s:
        "In the Western Meridian: corroborated strikes in Northern Kessel with a corrected injury range, interceptions over Ardenia's capital, drone-related suspension at Port Havren, and a second day of ceasefire talks in Nerath.",
      topDevelopments: [
        { text: "Northern Kessel strikes corroborated by two independent outlets.", sourceArticleIds: [aKesselWire.id, aKesselObserver.id] },
        { text: "Port Havren suspended operations over reported drone activity.", sourceArticleIds: [aDrone.id] },
      ],
      changedSincePrior: [],
      majorIncidentIds: ["inc-kessel-strike", "inc-drone-havren", "inc-ceasefire-talks"],
      diplomaticDevelopments: [
        { text: "Nerath talks extended into the evening.", sourceArticleIds: [aTalks3.id] },
      ],
      humanitarianImpact: [],
      conflictingReports: [
        { text: "Kessel injury figures remain disputed between provincial and national authorities.", sourceArticleIds: [aKesselDenial.id] },
      ],
      whatToWatch: [
        { text: "Scheduled address by Ardenia's prime minister.", sourceArticleIds: [] },
      ],
      corrections: [],
      demo: true,
    },
  ];

  return {
    countries,
    conflicts,
    sources,
    articles,
    claims,
    incidents,
    newsClusters,
    addresses,
    briefings,
  };
}

/** Article IDs backing each incident (kept separate from the Incident type —
 * the internal store joins these; they are never projected as raw lists). */
export function articleIdsForIncident(fx: FixtureSet, incidentId: string): string[] {
  const ids = new Set(
    fx.claims.filter((c) => c.incidentId === incidentId).map((c) => c.articleId),
  );
  for (const id of STATIC_ARTICLE_MAP[incidentId] ?? []) ids.add(id);
  return [...ids];
}

/** Deterministic article sets per incident, by article sequence position.
 * (Article IDs are assigned sequentially by buildFixtures.) */
const STATIC_ARTICLE_MAP: Record<string, string[]> = {
  "inc-kessel-strike": ["art-1", "art-2", "art-3", "art-4", "art-5", "art-6"],
  "inc-drone-havren": ["art-7"],
  "inc-ground-northline": ["art-8", "art-9"],
  "inc-aris-strait": ["art-10"],
  "inc-velmar-explosion": ["art-11"],
  "inc-interception-capital": ["art-12", "art-13", "art-14"],
  "inc-koris-protests": ["art-15", "art-16"],
  "inc-velmar-cyber": ["art-17"],
  "inc-ceasefire-talks": ["art-18", "art-19", "art-20"],
  "inc-sanctions-package": ["art-21", "art-22"],
  "inc-sundara-flood": ["art-23", "art-24"],
  "inc-ua-remarks": ["art-25"],
  "inc-nerath-bridge-retracted": ["art-26"],
  "inc-kessel-depot-archived": ["art-27", "art-28"],
  "inc-kessel-east-embargoed": ["art-29"],
  "inc-risk-withheld": [],
};
